---
  - name: Generate PFX file using client cert
    shell: |
        if [ ! -e {{tls_pfx_path}}/{{tls_client_authname}}.pfx ]
        then
        mkdir -p {{tls_pfx_path}}
        openssl pkcs12 -export -out {{tls_pfx_path}}/{{tls_client_authname}}.pfx -inkey {{cert_dir}}/{{tls_client_key}} -in {{cert_dir}}/{{tls_client_cert}} -certfile {{tls_ca_path}}/{{tls_ca_cert}} -password pass:{{tls_pfx_password}}
        fi
    args:
      executable: /bin/bash
    ignore_errors: true
    run_once: true

  - name: Fetch pfx cert to {{fetch_dest}}
    fetch:
      src: "{{tls_pfx_path}}/{{tls_client_authname}}.pfx"
      dest: "{{fetch_dest}}/{{tls_client_authname}}.pfx"
      flat: true
