---
  - name: generate pfx cert | generate PFX file using client cert for {{clients}}
    shell: |
        if [ ! -e {{cert_dir}}/{{ clients }}.pfx ]
        then
        mkdir -p {{cert_dir}}
        openssl pkcs12 -export -out {{cert_dir}}/{{ clients }}.pfx -inkey {{cert_dir}}/{{ clients }}.key -in {{cert_dir}}/{{ clients }}.pem -certfile {{tls_ca_path}}/{{tls_ca_cert}} -password pass:{{tls_pfx_password}}
        fi
    args:
      executable: /bin/bash
    ignore_errors: true
    run_once: true

  - name: generate pfx cert | fetch pfx cert to {{fetch_dest}} for {{clients}}
    fetch:
      src: "{{cert_dir}}/{{ clients }}.pfx"
      dest: "{{fetch_dest}}/{{ clients }}.pfx"
      flat: true

  - name: generate pfx cert | adding {{clients}} to authorized haproxy admin
    lineinfile:
      path: /etc/haproxy/authorized_admin
      line: "{{ clients }}"
      create: yes
    delegate_to: "{{ item }}"
    with_items:
      - "{{ haproxy_group }}"
