---
  - name: Generate CA cert
    import_tasks: generate-ca-cert.yml
    when:
      - generate_tls_certs
      - generate_ca_cert|bool

  - name: Generate client cert
    import_tasks: generate-client-cert.yml
    when:
      - generate_tls_certs
      - generate_client_cert|bool

  - name: Generate server cert
    import_tasks: generate-server-cert.yml
    when:
      - generate_tls_certs
      - generate_server_cert|bool

  - name: Generate pfx cert
    include_tasks: generate-pfx-cert.yml
    loop: "{{ tls_client_authname|flatten(levels=1) }}"
    loop_control:
      loop_var: "clients"
    when:
      - generate_tls_certs
      - generate_pfx_cert|bool

  - name: Copy certs
    import_tasks: copy-cert.yml
    when:
      - generate_tls_certs
      - copy_cert|bool
